sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: H9lwfULsqepYRBUQhhxbH6+X6Ctj7U4O3MIZNk0CRsoleza7DwtwtSQUU1X2Y85QW35BvHh1ujf4E4T31Xx+0D0MPS+C/ReNbydooWatlVu6KEFC45WJ62ujSR1RY8630b+HVrAXezFP4pJaehv/GcZWRRMzvdKUTkqX03iGuFKdZvvFfoyzwGsiLQQYq9JUDC84QP5UmjQKXft+xR9vJjrs3X1sG1lxIwN/o1sTS868O0QD5OHoNwon9CL4b7XbtPd+C5mIx8whUXIFN/I/XRd1RQtfHLRD02mI6PO2EGpl9a+PbdieESAg1Wrs8R8dWMbOjeO0/YFZbRh5sKR+rNlPrEF+uvsA8VnSJwmaq9MYrIamFHX91uTWpWMamDswKdq514SsCFJvQqW50PJ99emu/wVWA1GWKng8W1yIsM2bMnYh0iWBFk2ZyJhoqAzW0xqmgX2ncKLCxkj88f98Pv2AgVg+IyOmw8NN3UD3MVZCWKV8P7H/jRub8ldSIVISRlJLg2bIZVDEt9h8g1+dkAnu49UdshSzM30pSQ4QGMZGlGsWgDMF/eizQZeftwejJFTEOjcn0YqH9iCWi+M5taNpaJB5oka4Wo5RpQE/E0ex528wBt0RiasYIoI9h1fkKdjxDMfd/8LHCErWPtu6NTsBB5vFBg6WGYFsI+2MsQY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Travels-of-Sir-John-Mandeville_782
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy